// Seed data for Ambica Home Decor
export const CATEGORIES = [
  { name: 'Wall Decor', slug: 'wall-decor', icon: '🖼️', description: 'Elegant wall art and decorations' },
  { name: 'Showpieces', slug: 'showpieces', icon: '🏺', description: 'Decorative showpieces and sculptures' },
  { name: 'Mirrors', slug: 'mirrors', icon: '🪞', description: 'Designer mirrors and frames' },
  { name: 'Table Decor', slug: 'table-decor', icon: '🕯️', description: 'Beautiful table accents' },
  { name: 'Handmade Decor', slug: 'handmade-decor', icon: '🤲', description: 'Artisan handcrafted pieces' },
  { name: 'Luxury Accessories', slug: 'luxury-accessories', icon: '✨', description: 'Premium luxury accessories' },
  { name: 'Modern Decor', slug: 'modern-decor', icon: '🏠', description: 'Contemporary modern decor' },
  { name: 'Traditional Decor', slug: 'traditional-decor', icon: '🌺', description: 'Classic traditional pieces' },
];

export const STYLES = [
  { name: 'Modern Minimal', slug: 'modern-minimal', description: 'Clean lines, neutral tones' },
  { name: 'Luxury Gold', slug: 'luxury-gold', description: 'Opulent gold accents' },
  { name: 'Wooden Aesthetic', slug: 'wooden-aesthetic', description: 'Natural wood warmth' },
  { name: 'Contemporary', slug: 'contemporary', description: 'Current design trends' },
  { name: 'Traditional', slug: 'traditional', description: 'Timeless classical beauty' },
  { name: 'Artistic', slug: 'artistic', description: 'Bold artistic expression' },
];

export const MATERIALS = [
  'Wood', 'Metal', 'Glass', 'Ceramic', 'Fabric', 'Resin', 'Marble', 'Mixed Media',
];

export const SEED_PRODUCTS = [
  {
    name: 'Arch Frame Wall Art',
    slug: 'arch-frame-wall-art',
    description: 'A stunning architectural arch-inspired wall art piece crafted with precision. The geometric elegance brings a modern yet timeless appeal to any space. Each piece is handfinished for a premium quality result.',
    shortDescription: 'Architectural arch wall art in premium matte finish',
    category: 'Wall Decor',
    style: 'Modern Minimal',
    material: 'Metal',
    tags: ['abstract', 'arch', 'geometric', 'modern'],
    images: ['/cat-wall-decor.png'],
    dimensions: { width: '24"', height: '36"', depth: '2"' },
    featured: true,
  },
  {
    name: 'Boho Macramé Wall Hanging',
    slug: 'boho-macrame-wall-hanging',
    description: 'Handwoven macramé wall hanging using natural cotton rope. Each piece is uniquely crafted by skilled artisans, bringing texture and warmth to your interiors.',
    shortDescription: 'Handwoven natural cotton macramé wall piece',
    category: 'Handmade Decor',
    style: 'Artistic',
    material: 'Fabric',
    tags: ['boho', 'handmade', 'macrame', 'natural'],
    images: ['/style-modern-minimal.png'],
    dimensions: { width: '18"', height: '30"' },
    featured: true,
  },
  {
    name: 'Gold Leaf Mirror',
    slug: 'gold-leaf-mirror',
    description: 'An exquisite circular mirror with hand-applied gold leaf frame. A statement piece that adds opulence and reflects light beautifully in any room.',
    shortDescription: 'Circular mirror with hand-applied gold leaf frame',
    category: 'Mirrors',
    style: 'Luxury Gold',
    material: 'Glass',
    tags: ['gold', 'luxury', 'mirror', 'statement'],
    images: ['/cat-mirrors.png'],
    dimensions: { width: '28"', height: '28"', depth: '1"' },
    featured: true,
  },
  {
    name: 'Teak Wood Sculpture',
    slug: 'teak-wood-sculpture',
    description: 'Carved from solid teak wood, this abstract sculpture celebrates the natural grain and warmth of wood. A conversation piece for any living space.',
    shortDescription: 'Hand-carved solid teak abstract sculpture',
    category: 'Showpieces',
    style: 'Wooden Aesthetic',
    material: 'Wood',
    tags: ['wood', 'sculpture', 'handcarved', 'natural'],
    images: ['/cat-showpieces.png'],
    dimensions: { height: '18"', weight: '2.5 kg' },
    featured: true,
  },
  {
    name: 'Marble Vase Set',
    slug: 'marble-vase-set',
    description: 'A trio of marble-finish vases in graduating sizes. The natural stone texture creates a sophisticated and luxurious table display.',
    shortDescription: 'Set of 3 marble-finish luxury vases',
    category: 'Table Decor',
    style: 'Luxury Gold',
    material: 'Marble',
    tags: ['marble', 'vase', 'set', 'luxury'],
    images: ['/style-luxury-gold.png'],
    dimensions: { height: '6", 8", 12"' },
    featured: true,
  },
  {
    name: 'Brass Geometric Wall Panel',
    slug: 'brass-geometric-wall-panel',
    description: 'Hand-hammered brass wall panel with intricate geometric patterns. A masterpiece of traditional craftsmanship meets contemporary design.',
    shortDescription: 'Hand-hammered brass geometric wall panel',
    category: 'Traditional Decor',
    style: 'Traditional',
    material: 'Metal',
    tags: ['brass', 'geometric', 'traditional', 'handmade'],
    images: ['/hero-interior.png'],
    dimensions: { width: '20"', height: '30"', depth: '0.5"' },
    featured: false,
  },
  {
    name: 'Abstract Canvas Print',
    slug: 'abstract-canvas-print',
    description: 'Gallery-quality abstract art print on premium stretched canvas. Features muted earth tones that complement any neutral interior palette.',
    shortDescription: 'Premium gallery-quality abstract canvas art',
    category: 'Wall Decor',
    style: 'Contemporary',
    material: 'Mixed Media',
    tags: ['abstract', 'canvas', 'art', 'contemporary'],
    images: ['/gallery-1.png'],
    dimensions: { width: '32"', height: '48"' },
    featured: false,
  },
  {
    name: 'Rattan Pendant Lamp',
    slug: 'rattan-pendant-lamp',
    description: 'Artisanal rattan pendant lamp with warm amber glow. Creates beautiful shadow patterns and adds a bohemian luxury touch to any space.',
    shortDescription: 'Handwoven rattan pendant lamp with warm ambiance',
    category: 'Luxury Accessories',
    style: 'Wooden Aesthetic',
    material: 'Mixed Media',
    tags: ['rattan', 'lamp', 'lighting', 'boho'],
    images: ['/gallery-2.png'],
    dimensions: { width: '16"', height: '20"' },
    featured: false,
  },
];

export const SEED_TESTIMONIALS = [
  {
    name: 'Priya Sharma',
    role: 'Interior Designer',
    review: 'Ambica Home Decor has transformed my client projects. The quality and attention to detail in every piece is simply outstanding. My clients always ask where I source such beautiful decor.',
    rating: 5,
  },
  {
    name: 'Rahul Mehta',
    role: 'Homeowner',
    review: 'I purchased the gold leaf mirror for our living room and it has become the absolute focal point. The craftsmanship is impeccable and the customer service was exceptional.',
    rating: 5,
  },
  {
    name: 'Sunita Patel',
    role: 'Architect',
    review: 'As someone who works with premium spaces daily, I have very high standards. Ambica consistently delivers pieces that meet and exceed my expectations. Truly luxury decor.',
    rating: 5,
  },
  {
    name: 'Vikram Joshi',
    role: 'Property Developer',
    review: 'We furnished three luxury show apartments with Ambica pieces. The impact on buyer interest was immediate and significant. The brand truly elevates any space.',
    rating: 5,
  },
  {
    name: 'Anjali Desai',
    role: 'Lifestyle Blogger',
    review: 'Every piece from Ambica tells a story. The handmade collection is particularly special — you can feel the artistry and care in each item. Absolutely recommend!',
    rating: 5,
  },
];
